[package]
name = "cach"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-utils = "0.8.20"
hashbrown = { version = "0.14.5", features = ["raw"] }
index_list = "0.2.13"
parking_lot = "0.12.3"
slotmap = "1.0.7"
